name: wfmc
description: "Wimmera Flood Maps"
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  http: ^1.6.0
  xml: ^6.6.1
  shared_preferences: ^2.5.4
  latlong2: ^0.9.1
  pool: ^1.5.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.7
  vector_map_tiles: ^9.0.0-beta.8
  vector_map_tiles_pmtiles:
    git:
      url: https://github.com/josxha/flutter_map_plugins.git
      path: vector_map_tiles_pmtiles
  vector_tile_renderer: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_1024.png"
  adaptive_icon_background: "#C0D4EC"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"
  adaptive_icon_monochrome: "assets/app_icon_monochrome.png"

flutter_native_splash:
  color: "#000000"
  image: assets/splash_text.png
  fullscreen: false
  android_12:
    color: "#000000"
    image: assets/splash_text.png
    icon_background_color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/wcma_boundary.geojson
    - assets/legend.png
